# --- ÉTAPE 1 : Build du Frontend (Vite) ---
FROM node:20-alpine AS frontend-builder
WORKDIR /app/web
COPY ./web/package*.json ./
RUN npm install
COPY ./web/ ./
RUN npm run build

# --- ÉTAPE 2 : Image de Développement Go avec Air & Delve ---
FROM golang:1.25.5
WORKDIR /app

# Installation des outils de développement
RUN go install github.com/go-delve/delve/cmd/dlv@latest
RUN go install github.com/cosmtrek/air@latest

# Gestion des dépendances Go
COPY go.mod go.sum* ./
RUN go mod download

# Copie du code source
COPY . .

# Récupération du frontend compilé
COPY --from=frontend-builder /app/web/dist ./ui/dist

# On expose les ports applicatif (8080) et debug (40000)
EXPOSE 8080 40000

# L'ENTRYPOINT lance Air qui va gérer la compilation et Delve
ENTRYPOINT ["air", "-c", ".air.toml"]