package webapi

import (
	"fmt"
	"strings"
)

func mInit(key string) (string, error) {
	//create table roleS
	switch strings.ToLower(key) {
	case "role":
		return `CREATE OBJECT IF NOT EXISTS ROLE(CODE STRING(5) NOT NULL PRIMARY KEY, NAME STRING(25) NOT NULL)
				TRUNCATE OBJECT ROLE
				INSERT INTO ROLE(CODE,NAME)VALUES('admin','admin role')`, nil
	case "process":
		return fmt.Sprintf(`CREATE OBJECT IF NOT EXISTS PROCESS(CODE STRING(50) NOT NULL, ROLE STRING(5) NOT NULL, NAME STRING(75) NOT NULL, ID INTEGER(11) NOT NULL DEFAULT 0, CONSTRAINT PK_PROCESS PRIMARY KEY (CODE),CONSTRAINT FK_PROCESS_ROLE FOREIGN KEY (ROLE)REFERENCES ROLE(CODE))
				TRUNCATE OBJECT PROCESS
				INSERT INTO PROCESS(CODE,ROLE,NAME,ID)VALUES('%s','admin','%s',0)`, ConfigClient.Params["service_name"].(string), ConfigClient.Params["service_name"].(string)), nil
	case "knowledge":
		return `CREATE OBJECT IF NOT EXISTS KNOWLEDGE(GOAL STRING(250) NOT NULL, PROC STRING(6) NOT NULL, REFRESHABLE INTEGER(1) NOT NULL DEFAULT 0, EVEL INTEGER(1) NOT NULL DEFAULT 1, ID INTEGER(11) NOT NULL DEFAULT 0, CONSTRAINT PK_KNOWLEDGE PRIMARY KEY (GOAL, PROC),CONSTRAINT FK_KNOWLEDGE_PROCESS FOREIGN KEY(PROC)REFERENCES PROCESS(CODE))
				CREATE OBJECT IF NOT EXISTS TRANSACTION(NAME STRING(25) NOT NULL PRIMARY KEY, ID  INTEGER(11) NOT NULL DEFAULT 0)
				TRUNCATE OBJECT TRANSACTION
				INSERT INTO TRANSACTION(NAME,ID)VALUES('read',0)
				INSERT INTO TRANSACTION(NAME,ID)VALUES('insert',0)
				INSERT INTO TRANSACTION(NAME,ID)VALUES('update',0)
				INSERT INTO TRANSACTION(NAME,ID)VALUES('delete',0)
				INSERT INTO TRANSACTION(NAME,ID)VALUES('ddl_insert',0)
				INSERT INTO TRANSACTION(NAME,ID)VALUES('ddl_update',0)
				INSERT INTO TRANSACTION(NAME,ID)VALUES('ddl_delete',0)
				INSERT INTO TRANSACTION(NAME,ID)VALUES('ddl_read',0)
				CREATE OBJECT IF NOT EXISTS CONTEXT(GOAL STRING(250) NOT NULL, PROC STRING(6) NOT NULL, OBJECT STRING(25) NOT NULL, TRANS STRING(25) NOT NULL,ID  INTEGER(11) NOT NULL DEFAULT 0,CONSTRAINT PK_CONTEXT PRIMARY KEY(GOAL, PROC, OBJECT,TRANS),CONSTRAINT FK_CONTEXT_KNOWLEDGE FOREIGN KEY(GOAL,PROC)REFERENCES KNOWLEDGE(GOAL,PROC), CONSTRAINT  FK_CONTEXT_TRANSACTION FOREIGN KEY(TRANS) REFERENCES TRANSACTION(NAME))
				CREATE OBJECT IF NOT EXISTS RULE(GOAL STRING(250) NOT NULL, PROC STRING(6) NOT NULL,ACTION STRING(65000) NOT NULL, SCREEN STRING(65000) NOT NULL, CONSTRAINT PK_RULE PRIMARY KEY(GOAL,PROC),CONSTRAINT FK_RULE_KNOWLEDGE FOREIGN KEY(GOAL,PROC)REFERENCES KNOWLEDGE(GOAL,PROC))
				CREATE OBJECT IF NOT EXISTS FILTER(GOAL STRING(250) NOT NULL, PROC STRING(6) NOT NULL, OBJECT STRING(25) NOT NULL, EXPRESSSION STRING(500) NOT NULL, CONSTRAINT PK_FILTER PRIMARY KEY(GOAL,PROC,OBJECT), CONSTRAINT FK_FILTER_KNOWLEDGE FOREIGN KEY(GOAL,PROC)REFERENCES KNOWLEDGE(GOAL,PROC))
				CREATE OBJECT IF NOT EXISTS EXCLUDED(GOAL STRING(250) NOT NULL, PROC STRING(6) NOT NULL, ROLE STRING(5) NOT NULL, OBJECT STRING(25) NOT NULL, FIELD STRING(25) NOT NULL, CONSTRAINT PK_EXCLUDED PRIMARY KEY(ROLE, GOAL, PROC, OBJECT,FIELD), CONSTRAINT  FK_EXCLUDED_KNOWLEDGE FOREIGN KEY(GOAL,PROC)REFERENCES KNOWLEDGE(GOAL,PROC), CONSTRAINT  FK_EXCLUDED_ROLE FOREIGN KEY(ROLE) REFERENCES PROCESS(CODE))`, nil
	case "labels":
		return `CREATE OBJECT IF NOT EXISTS IDS(PROC STRING(6) NOT NULL,ID INTEGER(11) NOT NULL, CONSTRAINT PK_IDS  PRIMARY KEY(PROC,ID), CONSTRAINT FK_IDS_PROCESS FOREIGN KEY(PROC)REFERENCES PROCESS(CODE))
				CREATE OBJECT IF NOT EXISTS LAN(CODE STRING(4) NOT NULL, LABEL STRING(25) NOT NULL, ID INTEGER(11) NOT NULL DEFAULT 0, CONSTRAINT PK_LAN PRIMARY KEY(CODE))
				TRUNCATE OBJECT LAN
				INSERT INTO LAN(CODE, LABEL, ID)VALUES('fr','French',0)
				INSERT INTO LAN(CODE, LABEL, ID)VALUES('en','English',0)
				CREATE OBJECT IF NOT EXISTS LABEL(ID INTEGER(11) NOT NULL, PROC STRING(6) NOT NULL, LAN STRING(05) NOT NULL, LABEL STRING(1000) NOT NULL, CONSTRAINT PK_LABEL PRIMARY KEY(ID, PROC, LAN), CONSTRAINT FK_LABEL_IDS FOREIGN KEY(PROC)REFERENCES PROCESS(CODE),CONSTRAINT FK_LABEL_LAN FOREIGN KEY(LAN)REFERENCES LAN(CODE))`, nil
	case "contract":
		return `CREATE OBJECT IF NOT EXISTS CONTRACT(NAME STRING(50) NOT NULL, PROC STRING(6) NOT NULL, GOAL STRING(250) NOT NULL, CONSTRAINT PK_CONTRACT PRIMARY KEY(NAME), CONSTRAINT FK_CONTRACT_KNOWLEDGE FOREIGN KEY(GOAL,PROC)REFERENCES KNOWLEDGE(GOAL,PROC))
				CREATE OBJECT IF NOT EXISTS EVENT(URL STRING(250) NOT NULL,SUBJECT STRING(50) NOT NULL, PROC STRING(6) NOT NULL, GOAL STRING(250) NOT NULL, CONSTRAINT PK_EVENT PRIMARY KEY(PROC,URL,SUBJECT), CONSTRAINT FK_EVENT_KNOWLEDGE FOREIGN KEY(GOAL,PROC)REFERENCES KNOWLEDGE(GOAL,PROC))`, nil
	default:
		return "", fmt.Errorf("Key object '%s' not found", key)
	}
}
func genScriptInit() string {
	role, _ := mInit("role")
	proc, _ := mInit("process")
	knb, _ := mInit("knowledge")
	lbl, _ := mInit("labels")
	cont, _ := mInit("contract")
	return fmt.Sprintf(`Action 'Init a microservice'()
			 Start
			  %s
			  %s
			  %s
			  %s
			  %s
			 Stop`, role, proc, knb, lbl, cont)
}
