package webapi

import (
	"fmt"
	"strings"
)

func mInit(key string) (string, error) {
	//create table roleS
	switch strings.ToLower(key) {
	case "role":
		return `CREATE OBJECT IF NOT EXISTS ROLE(CODE VARCHAR(5) NOT NULL PRIMARY KEY, NAME VARCHAR(25) NOT NULL)
				INSERT INTO ROLE(CODE,NAME)VALUES('admin','admin role')`, nil
	case "process":
		return fmt.Sprintf(`CREATE OBJECT IF NOT EXISTS PROCESS(CODE VARCHAR(6) NOT NULL, ROLE VARCHAR(5) NOT NULL, NAME VARCHAR(25) NOT NULL, ID INTEGER NOT NULL DEFAULT 0, CONSTRAINT PK_PROCESS PRIMARY KEY (CODE),CONSTRAINT FK_PROCESS_ROLE FOREIGN KEY (ROLE)REFERENCES ROLE(CODE))
				INSERT INTO PROCESS(CODE,ROLE,NAME,ID)VALUES('%s','admin','%s',0)`, ConfigClient.Params["service_name"].(string), ConfigClient.Params["service_name"].(string)), nil
	case "knowledge":
		return `CREATE OBJECT IF NOT EXISTS KNOWLEDGE(GOAL VARCHAR(250) NOT NULL, PROC VARCHAR(6) NOT NULL, REFRESHABLE INTEGER(1) NOT NULL DEFAULT 0, EVEL INTEGER(1) NOT NULL DEFAULT 1, ID INTEGER NOT NULL DEFAULT 0, CONSTRAINT PK_KNOWLEDGE PRIMARY KEY (GOAL, PROC),CONSTRAINT FK_KNOWLEDGE_PROCESS FOREIGN KEY(PROC)REFERENCES PROCESS(CODE))
				CREATE OBJECT IF NOT EXISTS TRANSACTION(NAME VARCHAR(25) NOT NULL PRIMARY KEY, ID  INTEGER NOT NULL DEFAULT 0)
				CREATE OBJECT IF NOT EXISTS CONTEXT(GOAL VARCHAR(250) NOT NULL, PROC VARCHAR(6) NOT NULL, OBJECT VARCHAR(25) NOT NULL, TRANS VARCHAR(25) NOT NULL,ID  INTEGER NOT NULL DEFAULT 0,CONSTRAINT PK_CONTEXT PRIMARY KEY(GOAL, PROC, OBJECT,TRANS),CONSTRAINT FK_CONTEXT_KNOWLEDGE FOREIGN KEY(GOAL,PROC)REFERENCES KNOWLEDGE(GOAL,PROC), CONSTRAINT  FK_CONTEXT_TRANSACTION FOREIGN KEY(TRANS) REFERENCES TRANSACTION(NAME))
				CREATE OBJECT IF NOT EXISTS RULE(GOAL VARCHAR(250) NOT NULL, PROC VARCHAR(6) NOT NULL,ACTION TEXT NOT NULL, SCREEN TEXT NOT NULL, CONSTRAINT PK_RULE PRIMARY KEY(GOAL,PROC),CONSTRAINT FK_RULE_KNOWLEDGE FOREIGN KEY(GOAL,PROC)REFERENCES KNOWLEDGE(GOAL,PROC))
				CREATE OBJECT IF NOT EXISTS FILTER(GOAL VARCHAR(250) NOT NULL, PROC VARCHAR(6) NOT NULL, OBJECT VARCHAR(25) NOT NULL, EXPRESSSION VARCHAR(500) NOT NULL, CONSTRAINT PK_FILTER PRIMARY KEY(GOAL,PROC,OBJECT), CONSTRAINT FK_FILTER_KNOWLEDGE FOREIGN KEY(GOAL,PROC)REFERENCES KNOWLEDGE(GOAL,PROC))
				CREATE OBJECT IF NOT EXISTS EXCLUDED(GOAL VARCHAR(250) NOT NULL, PROC VARCHAR(6) NOT NULL, ROLE VARCHAR(5) NOT NULL, OBJECT VARCHAR(25) NOT NULL, FIELD VARCHAR(25) NOT NULL, CONSTRAINT PK_EXCLUDED PRIMARY KEY(ROLE, GOAL, PROC, OBJECT,FIELD), CONSTRAINT  FK_EXCLUDED_KNOWLEDGE FOREIGN KEY(GOAL,PROC)REFERENCES KNOWLEDGE(GOAL,PROC), CONSTRAINT  FK_EXCLUDED_ROLE FOREIGN KEY(ROLE) REFERENCES PROCESS(CODE))`, nil
	case "labels":
		return `CREATE OBJECT IF NOT EXISTS IDS(PROC VARCHAR(6) NOT NULL,ID INTEGER NOT NULL, CONSTRAINT PK_IDS  PRIMARY KEY(PROC,ID), CONSTRAINT FK_IDS_PROCESS FOREIGN KEY(PROC)REFERENCES PROCESS(CODE))
				CREATE OBJECT IF NOT EXISTS LAN(CODE VARCHAR(4) NOT NULL, LABEL VARCHAR(25) NOT NULL, ID INTEGER NOT NULL DEFAULT 0, CONSTRAINT PK_LAN PRIMARY KEY(CODE))
				CREATE OBJECT IF NOT EXISTS LABEL(ID INTEGER NOT NULL, PROC VARCHAR(6) NOT NULL, LAN VARCHAR(05) NOT NULL, LABEL VARCHAR(1000) NOT NULL, CONSTRAINT PK_LABEL PRIMARY KEY(ID, PROC, LAN), CONSTRAINT FK_LABEL_IDS FOREIGN KEY(PROC)REFERENCES PROCESS(CODE),CONSTRAINT FK_LABEL_LAN FOREIGN KEY(LAN)REFERENCES LAN(CODE))`, nil
	case "contract":
		return `CREATE OBJECT IF NOT EXISTS CONTRACT(NAME VARCHAR(50) NOT NULL, PROC VARCHAR(6) NOT NULL, GOAL VARCHAR(250) NOT NULL, CONSTRAINT PK_CONTRACT PRIMARY KEY(NAME), CONSTRAINT FK_CONTRACT_KNOWLEDGE FOREIGN KEY(GOAL,PROC)REFERENCES KNOWLEDGE(GOAL,PROC))
				CREATE OBJECT IF NOT EXISTS EVENT(URL VARCHAR(250) NOT NULL,SUBJECT VARCHAR(50) NOT NULL, PROC VARCHAR(6) NOT NULL, GOAL VARCHAR(250) NOT NULL, CONSTRAINT PK_EVENT PRIMARY KEY(PROC,URL,SUBJECT), CONSTRAINT FK_EVENT_KNOWLEDGE FOREIGN KEY(GOAL,PROC)REFERENCES KNOWLEDGE(GOAL,PROC))`, nil
	default:
		return "", fmt.Errorf("Key object '%s' not found", key)
	}
}
func genScriptInit() string {
	role, _ := mInit("role")
	proc, _ := mInit("process")
	knb, _ := mInit("knowledge")
	lbl, _ := mInit("labels")
	cont, _ := mInit("contract")
	return fmt.Sprintf(`Action 'Init a microservice'()
			 Start
			  %s
			  %s
			  %s
			  %s
			  %s
			 Stop`, role, proc, knb, lbl, cont)
}
