package webapi

import (
	"fmt"
	"strings"
)

func mInit(key string) (string, error) {
	//create table roleS
	switch strings.ToLower(key) {
	case "service":
		return fmt.Sprintf(`CREATE OBJECT IF NOT EXISTS SERV_DESC(NAME STRING(50) NOT NULL PRIMARY KEY, ICON STRING(25), ID INTEGER(11) NOT NULL DEFAULT 0)
		TRUNCATE OBJECT SERV_DESC 
		INSERT INTO SERV_DESC(NAME,ICON, ID)VALUES('%s','default',0)
		`, ConfigClient.Params["service_name"].(string)), nil
	case "role":
		return `CREATE OBJECT IF NOT EXISTS ROLE(CODE STRING(5) NOT NULL PRIMARY KEY, NAME STRING(50) NOT NULL)
				TRUNCATE OBJECT ROLE
				INSERT INTO ROLE(CODE,NAME)VALUES('admin','Administrator role')
				(* INSERT INTO ROLE(CODE,NAME)VALUES('dev','Developer role') *)
				`, nil
	case "process":
		return fmt.Sprintf(`CREATE OBJECT IF NOT EXISTS PROCESS(CODE STRING(50) NOT NULL, NAME STRING(75) NOT NULL, ID INTEGER(11) NOT NULL DEFAULT 0, STATUS INTEGER(1) NOT NULL DEFAULT 1, CONSTRAINT PK_PROCESS PRIMARY KEY (CODE))
				TRUNCATE OBJECT PROCESS
				INSERT INTO PROCESS(CODE,NAME,ID,STATUS)VALUES('initialization','Initialization of the %s',21,0)`, ConfigClient.Params["service_name"].(string)), nil
	case "knowledge":
		return `CREATE OBJECT IF NOT EXISTS KNOWLEDGE(GOAL STRING(250) NOT NULL, PROC STRING(50) NOT NULL, REFRESHABLE INTEGER(1) NOT NULL DEFAULT 0, LEVEL INTEGER(1) NOT NULL DEFAULT 1, ID INTEGER(11) NOT NULL DEFAULT 0, STATUS INTEGER(1) NOT NULL DEFAULT 1, CONSTRAINT PK_KNOWLEDGE PRIMARY KEY (GOAL, PROC),CONSTRAINT FK_KNOWLEDGE_PROCESS FOREIGN KEY(PROC)REFERENCES PROCESS(CODE))
				TRUNCATE OBJECT KNOWLEDGE
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('create knowledge','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('delete knowledge','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('look for knowledge','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('update the knowledge context','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('update the knowledge action','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('update the knowledge screen','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('update the knowledge context','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('assign the knowledge to a role','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('create roles','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('delete roles','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('look for roles','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('create processes','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('delete processes','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('update processes','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('look for processes','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('add a restriction','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('remove a restriction','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('look for restriction','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('add a filter','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('remove a filter','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('look for filter','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('generate ids','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('add labels','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('remove labels','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('update labels','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('look for labels','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('add a language','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('update a language','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('look for languages','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('remove languages','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('assign a label','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('create an organization','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('delete an organization','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('look for an organization','initialization',1,1,0,3)
				INSERT INTO KNOWLEDGE(GOAL,PROC,REFRESHABLE,LEVEL,ID,STATUS)VALUES('admin looks for data','initialization',1,1,0,3)
				
				CREATE OBJECT IF NOT EXISTS TRANSACTION(NAME STRING(25) NOT NULL PRIMARY KEY, ID  INTEGER(11) NOT NULL DEFAULT 0)
				TRUNCATE OBJECT TRANSACTION
				INSERT INTO TRANSACTION(NAME,ID)VALUES('read',0)
				INSERT INTO TRANSACTION(NAME,ID)VALUES('insert',0)
				INSERT INTO TRANSACTION(NAME,ID)VALUES('update',0)
				INSERT INTO TRANSACTION(NAME,ID)VALUES('delete',0)
				INSERT INTO TRANSACTION(NAME,ID)VALUES('ddl_insert',0)
				INSERT INTO TRANSACTION(NAME,ID)VALUES('ddl_update',0)
				INSERT INTO TRANSACTION(NAME,ID)VALUES('ddl_delete',0)
				INSERT INTO TRANSACTION(NAME,ID)VALUES('ddl_read',0)

				CREATE OBJECT IF NOT EXISTS CONTEXT(GOAL STRING(250) NOT NULL, PROC STRING(50) NOT NULL, OBJECT STRING(50) NOT NULL, TRANS STRING(25) NOT NULL,ID  INTEGER(11) NOT NULL DEFAULT 0,CONSTRAINT PK_CONTEXT PRIMARY KEY(GOAL, PROC, OBJECT,TRANS),CONSTRAINT FK_CONTEXT_KNOWLEDGE FOREIGN KEY(GOAL,PROC)REFERENCES KNOWLEDGE(GOAL,PROC), CONSTRAINT  FK_CONTEXT_TRANSACTION FOREIGN KEY(TRANS) REFERENCES TRANSACTION(NAME))
				TRUNCATE OBJECT CONTEXT
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('create knowledge','initialization','KNOWLEDGE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('create knowledge','initialization','KNOWLEDGE','insert',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('create knowledge','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('create knowledge','initialization','RULE','insert',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('create knowledge','initialization','CONTEXT','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('create knowledge','initialization','CONTEXT','insert',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('create knowledge','initialization','PROCESS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('create knowledge','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('delete knowledge','initialization','KNOWLEDGE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('delete knowledge','initialization','KNOWLEDGE','delete',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('delete knowledge','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('delete knowledge','initialization','RULE','delete',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('delete knowledge','initialization','CONTEXT','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('delete knowledge','initialization','CONTEXT','delete',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('delete knowledge','initialization','PROCESS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('delete knowledge','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for knowledge','initialization','KNOWLEDGE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for knowledge','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for knowledge','initialization','CONTEXT','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for knowledge','initialization','PROCESS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for knowledge','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update the knowledge context','initialization','KNOWLEDGE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update the knowledge context','initialization','CONTEXT','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update the knowledge context','initialization','CONTEXT','delete',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update the knowledge context','initialization','CONTEXT','update',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update the knowledge context','initialization','PROCESS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update the knowledge context','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update the knowledge context','initialization','TRANSACTION','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update the knowledge context','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update the knowledge context','initialization','information_schema.tables','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update the knowledge action','initialization','KNOWLEDGE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update the knowledge action','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update the knowledge action','initialization','RULE','update',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update the knowledge action','initialization','CONTEXT','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update the knowledge action','initialization','PROCESS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update the knowledge action','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update the knowledge action','initialization','information_schema.tables','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update the knowledge screen','initialization','KNOWLEDGE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update the knowledge screen','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update the knowledge screen','initialization','RULE','update',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update the knowledge screen','initialization','CONTEXT','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update the knowledge screen','initialization','PROCESS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update the knowledge screen','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update the knowledge screen','initialization','information_schema.tables','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('assign the knowledge to a role','initialization','PROCESS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('assign the knowledge to a role','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('assign the knowledge to a role','initialization','KNOWLEDGE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('assign the knowledge to a role','initialization','ROLE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('assign the knowledge to a role','initialization','ROLES','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('assign the knowledge to a role','initialization','ROLES','delete',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('assign the knowledge to a role','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('create roles','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('create roles','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('create roles','initialization','ROLE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('create roles','initialization','ROLE','insert',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('delete roles','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('delete roles','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('delete roles','initialization','ROLE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('delete roles','initialization','ROLE','delete',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for roles','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for roles','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for roles','initialization','ROLE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('create processes','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('create processes','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('create processes','initialization','PROCESS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('create processes','initialization','PROCESS','insert',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('delete processes','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('delete processes','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('delete processes','initialization','PROCESS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('delete processes','initialization','PROCESS','delete',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update processes','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update processes','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update processes','initialization','PROCESS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update processes','initialization','PROCESS','update',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for processes','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for processes','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for processes','initialization','PROCESS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('add a restriction','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('add a restriction','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('add a restriction','initialization','CONTEXT','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('add a restriction','initialization','PROCESS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('add a restriction','initialization','KNOWLEDGE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('add a restriction','initialization','EXCLUDED','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('add a restriction','initialization','EXCLUDED','insert',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('add a restriction','initialization','information_schema.columns','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('add a restriction','initialization','ROLE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('remove a restriction','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('remove a restriction','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('remove a restriction','initialization','CONTEXT','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('remove a restriction','initialization','PROCESS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('remove a restriction','initialization','KNOWLEDGE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('remove a restriction','initialization','EXCLUDED','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('remove a restriction','initialization','EXCLUDED','delete',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('remove a restriction','initialization','ROLE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for restriction','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for restriction','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for restriction','initialization','CONTEXT','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for restriction','initialization','PROCESS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for restriction','initialization','KNOWLEDGE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for restriction','initialization','EXCLUDED','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for restriction','initialization','ROLE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('add a filter','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('add a filter','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('add a filter','initialization','CONTEXT','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('add a filter','initialization','PROCESS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('add a filter','initialization','KNOWLEDGE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('add a filter','initialization','FILTER','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('add a filter','initialization','FILTER','insert',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('add a filter','initialization','ROLE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('remove a filter','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('remove a filter','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('remove a filter','initialization','CONTEXT','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('remove a filter','initialization','PROCESS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('remove a filter','initialization','KNOWLEDGE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('remove a filter','initialization','FILTER','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('remove a filter','initialization','FILTER','delete',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('remove a filter','initialization','ROLE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for filter','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for filter','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for filter','initialization','CONTEXT','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for filter','initialization','PROCESS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for filter','initialization','KNOWLEDGE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for filter','initialization','FILTER','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for filter','initialization','ROLE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('generate ids','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('generate ids','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('generate ids','initialization','PROCESS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('generate ids','initialization','IDS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('generate ids','initialization','IDS','insert',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('add labels','initialization','IDS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('add labels','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('add labels','initialization','LABEL','insert',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('add labels','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('add labels','initialization','PROCESS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('add labels','initialization','LAN','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('remove labels','initialization','IDS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('remove labels','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('remove labels','initialization','LABEL','delete',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('remove labels','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('remove labels','initialization','PROCESS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('remove labels','initialization','LAN','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update labels','initialization','IDS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update labels','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update labels','initialization','LABEL','update',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update labels','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update labels','initialization','PROCESS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update labels','initialization','LAN','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for labels','initialization','IDS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for labels','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for labels','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for labels','initialization','PROCESS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for labels','initialization','LAN','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('add a language','initialization','IDS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('add a language','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('add a language','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('add a language','initialization','LAN','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('add a language','initialization','LAN','insert',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update a language','initialization','IDS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update a language','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update a language','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update a language','initialization','LAN','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('update a language','initialization','LAN','update',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for languages','initialization','IDS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for languages','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for languages','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for languages','initialization','LAN','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('remove languages','initialization','IDS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('remove languages','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('remove languages','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('remove languages','initialization','LAN','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('remove languages','initialization','LAN','delete',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('assign a label','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('assign a label','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('assign a label','initialization','KNOWLEDGE','update',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('assign a label','initialization','LAN','update',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('assign a label','initialization','PROCESS','update',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('assign a label','initialization','SERV_DESC','update',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('assign a label','initialization','KNOWLEDGE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('assign a label','initialization','LAN','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('assign a label','initialization','PROCESS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('assign a label','initialization','SERV_DESC','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('create an organization','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('create an organization','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('create an organization','initialization','ORGANIZATION','update',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('create an organization','initialization','ORGANIZATION','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('create an organization','initialization','PROCESS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('delete an organization','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('delete an organization','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('delete an organization','initialization','ORGANIZATION','delete',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('delete an organization','initialization','ORGANIZATION','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('delete an organization','initialization','PROCESS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for an organization','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for an organization','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for an organization','initialization','ORGANIZATION','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('look for an organization','initialization','PROCESS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('admin looks for data','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('admin looks for data','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('admin looks for data','initialization','ORGANIZATION','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('admin looks for data','initialization','PROCESS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('admin looks for data','initialization','ROLE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('admin looks for data','initialization','CONTEXT','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('admin looks for data','initialization','CONTRACT','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('admin looks for data','initialization','EVENT','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('admin looks for data','initialization','EXCLUDED','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('admin looks for data','initialization','FILTER','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('admin looks for data','initialization','IDS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('admin looks for data','initialization','KNOWLEDGE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('admin looks for data','initialization','LABEL','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('admin looks for data','initialization','LAN','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('admin looks for data','initialization','ORGANIZATION','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('admin looks for data','initialization','PROCESS','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('admin looks for data','initialization','ROLES','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('admin looks for data','initialization','RULE','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('admin looks for data','initialization','SERV_DESC','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('admin looks for data','initialization','TRANSACTION','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('admin looks for data','initialization','SYSTEM','ddl_read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('admin looks for data','initialization','SYSTEM','ddl_insert',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('admin looks for data','initialization','SYSTEM','ddl_delete',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('admin looks for data','initialization','SYSTEM','ddl_update',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('admin looks for data','initialization','information_schema.columns','read',0)
				INSERT INTO CONTEXT(GOAL, PROC,OBJECT,TRANS,ID)VALUES('admin looks for data','initialization','information_schema.tables','read',0)

				CREATE OBJECT IF NOT EXISTS RULE(GOAL STRING(250) NOT NULL, PROC STRING(50) NOT NULL,ACTION STRING(65000) NOT NULL, SCREEN STRING(65000) NOT NULL, CONSTRAINT PK_RULE PRIMARY KEY(GOAL,PROC),CONSTRAINT FK_RULE_KNOWLEDGE FOREIGN KEY(GOAL,PROC)REFERENCES KNOWLEDGE(GOAL,PROC))
				TRUNCATE OBJECT RULE
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('create knowledge','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('delete knowledge','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('look for knowledge','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('update the knowledge context','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('update the knowledge action','initialization','QWN0aW9uICd1cGRhdGUgdGhlIGtub3dsZWRnZSBhY3Rpb24nKGdvYWw6c3RyaW5nKDI1MCksIHByb2M6c3RyaW5nKDUwKSxzcmM6c3RyaW5nKDY1MDAwKSk6UmVzcG9uc2UKICBUeXBlIFJlc3BvbnNlIHN0cnVjdCB7CiAgICBzdGF0dXM6c3RyaW5nKDIpCiAgICBtc2c6c3RyaW5nKDUwKQogIH0KU3RhcnQKICBsZXQgcmVzPVJlc3BvbnNle21zZzonJywgc3RhdHVzOidvayd9CiAgaWYgbGVuKHNyYyk9PTB7CiAgICByZXMubXNnPSdFbXB0eSBhY3Rpb24nCiAgICByZXMuc3RhdHVzPSdrbycKICAgIHJldHVybiByZXMKICB9CiAgTGV0IGlzRGVmaW5lZCA9IGZhbHNlCiAgbGV0IHN0YXR1czogaW50ZWdlcj0wCiAgZm9yIGxldCB4IG9mIHNlbGVjdCBydWxlLnByb2MsIGsuc3RhdHVzIAogICAgICAgICAgICAgICBmcm9tIHJ1bGUgaW5uZXIgam9pbiBrbm93bGVkZ2UgayBvbihrLmdvYWw9PXJ1bGUuZ29hbCBhbmQgay5wcm9jPT1ydWxlLnByb2MpCiAgICAgICAgICAgICAgIHdoZXJlIHJ1bGUucHJvYz09cHJvYyBhbmQgcnVsZS5nb2FsPT1nb2FsewogICAgaXNEZWZpbmVkPXRydWUKICAgIHN0YXR1cz14LnN0YXR1cwogICAgYnJlYWsKICB9CiAgaWYgc3RhdHVzPj0zewogICAgcmVzLnN0YXR1cz0na28nCiAgICByZXMubXNnPSdhY3Rpb24gaXMgbm90IGF2YWlsYWJsZSBmb3IgbW9kaWZpY2F0aW9uJwogICAgcmV0dXJuIHJlcwogIH0KICBpZiBpc0RlZmluZWR7CiAgICB1cGRhdGUgcnVsZSBzZXQgYWN0aW9uPXNyYyB3aGVyZSBydWxlLnByb2M9PXByb2MgYW5kIHJ1bGUuZ29hbD09Z29hbAogICAgcmV0dXJuIHJlcwogIH0KICgqIGluc2VydCBpbnRvIHJ1bGUoZ29hbCwgcHJvYywgYWN0aW9uLCBzY3JlZW4pdmFsdWVzKGdvYWwscHJvYyxzcmMsJycpICopCiAgcmV0dXJuIHJlcwpTdG9w','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('update the knowledge screen','initialization','QWN0aW9uICd1cGRhdGUgdGhlIGtub3dsZWRnZSBzY3JlZW4nKGdvYWw6c3RyaW5nKDI1MCksIHByb2M6c3RyaW5nKDUwKSxzcmM6c3RyaW5nKDY1MDAwKSk6UmVzcG9uc2UKICBUeXBlIFJlc3BvbnNlIHN0cnVjdCB7CiAgICBzdGF0dXM6c3RyaW5nKDIpCiAgICBtc2c6c3RyaW5nKDUwKQogIH0KU3RhcnQKICBsZXQgcmVzPVJlc3BvbnNle21zZzonJywgc3RhdHVzOidvayd9CiAgaWYgbGVuKHNyYyk9PTB7CiAgICByZXMubXNnPSdFbXB0eSBzY3JlZW4nCiAgICByZXMuc3RhdHVzPSdrbycKICAgIHJldHVybiByZXMKICB9CiAgTGV0IGlzRGVmaW5lZCA9IGZhbHNlCiAgbGV0IHN0YXR1czogaW50ZWdlcj0wCiAgZm9yIGxldCB4IG9mIHNlbGVjdCBydWxlLnByb2MsIGsuc3RhdHVzIAogICAgICAgICAgICAgICBmcm9tIHJ1bGUgaW5uZXIgam9pbiBrbm93bGVkZ2UgayBvbihrLmdvYWw9PXJ1bGUuZ29hbCBhbmQgay5wcm9jPT1ydWxlLnByb2MpCiAgICAgICAgICAgICAgIHdoZXJlIHJ1bGUucHJvYz09cHJvYyBhbmQgcnVsZS5nb2FsPT1nb2FsewogICAgaXNEZWZpbmVkPXRydWUKICAgIHN0YXR1cz14LnN0YXR1cwogICAgYnJlYWsKICB9CiAgaWYgc3RhdHVzPj0zewogICAgcmVzLnN0YXR1cz0na28nCiAgICByZXMubXNnPSdzY3JlZW4gaXMgbm90IGF2YWlsYWJsZSBmb3IgbW9kaWZpY2F0aW9uJwogICAgcmV0dXJuIHJlcwogIH0KICBpZiBpc0RlZmluZWR7CiAgICB1cGRhdGUgcnVsZSBzZXQgc2NyZWVuPXNyYyB3aGVyZSBydWxlLnByb2M9PXByb2MgYW5kIHJ1bGUuZ29hbD09Z29hbAogICAgcmV0dXJuIHJlcwogIH0KICgqIGluc2VydCBpbnRvIHJ1bGUoZ29hbCwgcHJvYywgYWN0aW9uLCBzY3JlZW4pdmFsdWVzKGdvYWwscHJvYywnJyxzcmMpICopCiAgcmV0dXJuIHJlcwpTdG9w','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('assign the knowledge to a role','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('create roles','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('delete roles','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('look for roles','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('create processes','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('delete processes','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('update processes','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('look for processes','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('add a restriction','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('remove a restriction','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('look for restriction','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('add a filter','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('remove a filter','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('look for filter','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('generate ids','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('add labels','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('remove labels','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('update labels','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('look for labels','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('add a language','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('update a language','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('look for languages','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('remove languages','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('assign a label','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('create an organization','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('delete an organization','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('look for an organization','initialization','','')
				INSERT INTO RULE(GOAL, PROC, ACTION, SCREEN)VALUES('admin looks for data','initialization','','')

				CREATE OBJECT IF NOT EXISTS FILTER(GOAL STRING(250) NOT NULL, PROC STRING(50) NOT NULL, OBJECT STRING(25) NOT NULL, EXPRESSSION STRING(500) NOT NULL, CONSTRAINT PK_FILTER PRIMARY KEY(GOAL,PROC,OBJECT), CONSTRAINT FK_FILTER_KNOWLEDGE FOREIGN KEY(GOAL,PROC)REFERENCES KNOWLEDGE(GOAL,PROC))
				CREATE OBJECT IF NOT EXISTS EXCLUDED(GOAL STRING(250) NOT NULL, PROC STRING(50) NOT NULL, ROLE STRING(5) NOT NULL, OBJECT STRING(25) NOT NULL, FIELD STRING(25) NOT NULL, CONSTRAINT PK_EXCLUDED PRIMARY KEY(ROLE, GOAL, PROC, OBJECT,FIELD), CONSTRAINT  FK_EXCLUDED_KNOWLEDGE FOREIGN KEY(GOAL,PROC)REFERENCES KNOWLEDGE(GOAL,PROC), CONSTRAINT  FK_EXCLUDED_ROLE FOREIGN KEY(ROLE) REFERENCES PROCESS(CODE))
				TRUNCATE OBJECT EXCLUDED
				INSERT INTO EXCLUDED(GOAL, PROC, ROLE,OBJECT,FIELD)VALUES('assign a label','initialization','admin','KNOWLEDGE','GOAL')
				INSERT INTO EXCLUDED(GOAL, PROC, ROLE,OBJECT,FIELD)VALUES('assign a label','initialization','admin','KNOWLEDGE','PROC')
				INSERT INTO EXCLUDED(GOAL, PROC, ROLE,OBJECT,FIELD)VALUES('assign a label','initialization','admin','KNOWLEDGE','REFRESHABLE')
				INSERT INTO EXCLUDED(GOAL, PROC, ROLE,OBJECT,FIELD)VALUES('assign a label','initialization','admin','KNOWLEDGE','LEVEL')
				INSERT INTO EXCLUDED(GOAL, PROC, ROLE,OBJECT,FIELD)VALUES('assign a label','initialization','admin','KNOWLEDGE','STATUS')
				INSERT INTO EXCLUDED(GOAL, PROC, ROLE,OBJECT,FIELD)VALUES('assign a label','initialization','admin','LAN','CODE')
				INSERT INTO EXCLUDED(GOAL, PROC, ROLE,OBJECT,FIELD)VALUES('assign a label','initialization','admin','LAN','LABEL')
				INSERT INTO EXCLUDED(GOAL, PROC, ROLE,OBJECT,FIELD)VALUES('assign a label','initialization','admin','PROCESS','CODE')
				INSERT INTO EXCLUDED(GOAL, PROC, ROLE,OBJECT,FIELD)VALUES('assign a label','initialization','admin','PROCESS','NAME')
				INSERT INTO EXCLUDED(GOAL, PROC, ROLE,OBJECT,FIELD)VALUES('assign a label','initialization','admin','PROCESS','STATUS')
				INSERT INTO EXCLUDED(GOAL, PROC, ROLE,OBJECT,FIELD)VALUES('assign a label','initialization','admin','SERV_DESC','NAME')
				INSERT INTO EXCLUDED(GOAL, PROC, ROLE,OBJECT,FIELD)VALUES('assign a label','initialization','admin','SERV_DESC','ICON')

				CREATE OBJECT IF NOT EXISTS ORGANIZATION(ID INTEGER(5) NOT NULL,PROC STRING(50) NOT NULL,ICON STRING(25), IDPERE INTEGER(5) NOT NULL DEFAULT 0, LABELID INTEGER(11) NOT NULL DEFAULT 0, NOORDER INTEGER(2) NOT NULL DEFAULT 0, CONSTRAINT PK_ORGANIZATION PRIMARY KEY(ID,PROC), CONSTRAINT FK_ORGANIZATION_PROCESS FOREIGN KEY(PROC)REFERENCES PROCESS(CODE), CONSTRAINT FK_ORGANIZATION_LABEL FOREIGN KEY(LABELID,PROC)REFERENCES IDS(ID,PROC))
				TRUNCATE OBJECT ORGANIZATION

				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(1,'initialization',1,12,1,'brain')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(11,'initialization',1,1,11,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(12,'initialization',1,4,12,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(121,'initialization',12,14,121,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(122,'initialization',12,13,122,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(123,'initialization',12,15,123,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(13,'initialization',1,2,13,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(14,'initialization',1,3,14,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(15,'initialization',1,16,15,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(151,'initialization',15,6,151,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(152,'initialization',15,7,152,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(153,'initialization',15,3,153,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(16,'initialization',1,17,16,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(161,'initialization',16,6,161,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(162,'initialization',16,7,162,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(163,'initialization',16,3,163,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(17,'initialization',1,5,17,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(171,'initialization',17,10,171,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(172,'initialization',17,20,172,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(18,'initialization',1,18,18,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(181,'initialization',18,1,181,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(182,'initialization',18,2,182,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(183,'initialization',18,3,183,'')

				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(2,'initialization',2,10,2,'roles')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(21,'initialization',2,1,21,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(22,'initialization',2,2,22,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(23,'initialization',2,3,23,'')

				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(3,'initialization',3,11,3,'process')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(31,'initialization',3,1,31,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(32,'initialization',3,4,32,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(33,'initialization',3,2,33,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(34,'initialization',3,3,34,'')

				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(4,'initialization',4,20,4,'labels')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(41,'initialization',4,8,41,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(42,'initialization',4,6,42,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(43,'initialization',4,4,43,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(44,'initialization',4,2,44,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(45,'initialization',4,3,45,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(46,'initialization',4,9,46,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(461,'initialization',46,6,461,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(462,'initialization',46,7,462,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(463,'initialization',46,4,463,'')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(464,'initialization',46,3,464,'')

				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(5,'initialization',5,21,5,'datas')
				INSERT INTO ORGANIZATION(ID,PROC,IDPERE,LABELID,NOORDER,ICON)VALUES(51,'initialization',5,22,51,'')

				CREATE OBJECT IF NOT EXISTS ROLES(PROC STRING(50) NOT NULL, ROLE STRING(5) NOT NULL,GOAL STRING(250) NOT NULL,ID INTEGER(5), CPNT string(25), CONSTRAINT PK_ROLES PRIMARY KEY (PROC, ROLE, GOAL,ID), CONSTRAINT FK_ROLES_KNOWLEDGE FOREIGN KEY(PROC,GOAL)REFERENCES KNOWLEDGE(PROC,GOAL), CONSTRAINT FK_ROLES_ROLE FOREIGN KEY(ROLE)REFERENCES ROLE(CODE), CONSTRAINT FK_ROLES_ORGANIZATION FOREIGN KEY(PROC,ID)REFERENCES ORGANIZATION(PROC,ID))
				TRUNCATE OBJECT ROLES
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','create knowledge',11,'./Screen')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','delete knowledge',13,'./Screen')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','look for knowledge',14,'./Screen')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','update the knowledge context',122,'./Screen')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','update the knowledge action',121,'./Action') 
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','update the knowledge screen',123,'./FormBuilder') 
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','assign the knowledge to a role',171,'./Screen')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','admin looks for data',51,'./Query')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','create roles',21,'./Screen')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','delete roles',22,'./Screen')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','look for roles',23,'./Screen')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','create processes',31,'./Screen')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','delete processes',33,'./Screen')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','update processes',32,'./Screen')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','look for processes',34,'./Screen')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','add a restriction',161,'./Screen')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','remove a restriction',162,'./Screen')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','look for restriction',163,'./Screen')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','add a filter',151,'./Screen')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','remove a filter',152,'./Screen')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','look for filter',153,'./Screen')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','generate ids',41,'./Screen')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','add labels',42,'./Screen')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','remove labels',44,'./Screen')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','update labels',43,'./Screen')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','look for labels',45,'./Screen')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','add a language',461,'./Screen')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','remove languages',462,'./Screen')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','update a language',463,'./Screen')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','look for languages',464,'./Screen')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','assign a label',172,'./Screen')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','create an organization',181,'./Screen')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','delete an organization',182,'./Screen')
				INSERT INTO ROLES(PROC,ROLE,GOAL,ID,CPNT)VALUES('initialization','admin','look for an organization',183,'./Screen')

				`, nil
	case "labels":
		return `CREATE OBJECT IF NOT EXISTS IDS(PROC STRING(50) NOT NULL,ID INTEGER(11) NOT NULL, CONSTRAINT PK_IDS  PRIMARY KEY(PROC,ID), CONSTRAINT FK_IDS_PROCESS FOREIGN KEY(PROC)REFERENCES PROCESS(CODE))
				TRUNCATE OBJECT IDS
				for let x=0;x<200;x=x+1{
					INSERT INTO IDS(PROC,ID)VALUES('initialization',x)
				}
				CREATE OBJECT IF NOT EXISTS LAN(CODE STRING(4) NOT NULL, LABEL STRING(25) NOT NULL, ID INTEGER(11) NOT NULL DEFAULT 0, CONSTRAINT PK_LAN PRIMARY KEY(CODE))
				TRUNCATE OBJECT LAN
				INSERT INTO LAN(CODE, LABEL, ID)VALUES('fr','French',0)
				INSERT INTO LAN(CODE, LABEL, ID)VALUES('en','English',0)
				CREATE OBJECT IF NOT EXISTS LABEL(ID INTEGER(11) NOT NULL, PROC STRING(50) NOT NULL, LAN STRING(05) NOT NULL, LABEL STRING(1000) NOT NULL, CONSTRAINT PK_LABEL PRIMARY KEY(ID, PROC, LAN), CONSTRAINT FK_LABEL_IDS FOREIGN KEY(PROC)REFERENCES PROCESS(CODE),CONSTRAINT FK_LABEL_LAN FOREIGN KEY(LAN)REFERENCES LAN(CODE))
				TRUNCATE OBJECT LABEL
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(0,'initialization','fr','sans label')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(0,'initialization','en','no label')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(1,'initialization','fr','Créer')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(1,'initialization','en','Create')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(2,'initialization','fr','Supprimer')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(2,'initialization','en','Delete')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(3,'initialization','fr','Rechercher')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(3,'initialization','en','Look for')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(4,'initialization','fr','Modifier')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(4,'initialization','en','Update')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(5,'initialization','fr','Assigner')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(5,'initialization','en','Assign')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(6,'initialization','fr','Ajouter')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(6,'initialization','en','Add')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(7,'initialization','fr','Retirer')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(7,'initialization','en','Remove')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(8,'initialization','fr','Générer')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(8,'initialization','en','Generate')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(9,'initialization','fr','Langue')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(9,'initialization','en','Language')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(10,'initialization','fr','Rôle')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(10,'initialization','en','Role')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(11,'initialization','fr','Processus')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(11,'initialization','en','Process')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(12,'initialization','fr','Connaissance')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(12,'initialization','en','Knowledge')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(13,'initialization','fr','Contexte')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(13,'initialization','en','Context')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(14,'initialization','fr','Action')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(14,'initialization','en','Action')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(15,'initialization','fr','Écran')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(15,'initialization','en','Screen')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(16,'initialization','fr','Filtre')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(16,'initialization','en','Filter')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(17,'initialization','fr','Restriction')	
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(17,'initialization','en','Restriction')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(18,'initialization','fr','Organisation')	
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(18,'initialization','en','Organization')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(19,'initialization','fr','Identifiant')	
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(19,'initialization','en','Identifier')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(20,'initialization','fr','Libellé')	
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(20,'initialization','en','Label')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(21,'initialization','fr','Système')	
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(21,'initialization','en','System')
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(22,'initialization','fr','Données')	
				INSERT INTO LABEL(ID, PROC, LAN, LABEL)VALUES(22,'initialization','en','Datas')

				`, nil
	case "contract":
		return `CREATE OBJECT IF NOT EXISTS CONTRACT(NAME STRING(50) NOT NULL, PROC STRING(50) NOT NULL, GOAL STRING(250) NOT NULL, CONSTRAINT PK_CONTRACT PRIMARY KEY(NAME), CONSTRAINT FK_CONTRACT_KNOWLEDGE FOREIGN KEY(GOAL,PROC)REFERENCES KNOWLEDGE(GOAL,PROC))
				CREATE OBJECT IF NOT EXISTS EVENT(URL STRING(250) NOT NULL,SUBJECT STRING(50) NOT NULL, PROC STRING(50) NOT NULL, GOAL STRING(250) NOT NULL, CONSTRAINT PK_EVENT PRIMARY KEY(PROC,URL,SUBJECT), CONSTRAINT FK_EVENT_KNOWLEDGE FOREIGN KEY(GOAL,PROC)REFERENCES KNOWLEDGE(GOAL,PROC))`, nil
	default:
		return "", fmt.Errorf("Key object '%s' not found", key)
	}
}
func genScriptInit() string {
	serv, _ := mInit("service")
	role, _ := mInit("role")
	proc, _ := mInit("process")
	knb, _ := mInit("knowledge")
	lbl, _ := mInit("labels")
	cont, _ := mInit("contract")
	return fmt.Sprintf(`Action 'Init a microservice'()
			 Start
			  %s
			  %s
			  %s
			  %s
			  %s
			  %s
			 Stop`, serv, role, proc, lbl, knb, cont)
}
